# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_LEMOTE_YEELOONG2F)	+= yeeloong_laptop.o
CFLAGS_yeeloong_laptop.o = -I$(srctree)/arch/mips/loongson/lemote-2f
obj-$(CONFIG_CPU_HWMON) += cpu_hwmon.o
obj-$(CONFIG_RS780E_ACPI) += rs780e-acpi.o
